
trigger:
  branches:
    include:
      - trunk
  tags:
    include:
      - 'v*'
  paths:
    exclude:
      - azure-pipelines.yml
      - azure-pipelines-release.yml

pr:
  branches:
    include:
      - trunk
      - release-v*
      - hotfix-v*

resources:
  repositories:
    - repository: templates
      type: github
      name: BellevueCollege/bc-wordpress-devops-templates
      endpoint: github-service-connection

extends:
  template: templates/ci/plugin-ci.yml@templates
  parameters:

    pluginName: 'bc-final-exam-display'

    testEnvironments:
      - name: KinstaCstage
        displayName: 'Kinsta: CStage'
        environment: kinsta-cstage
        sshServiceConnection: 'cstage'
        variableGroup: kinsta-cstage

    runComposer: false

    buildSteps:
      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: 'run build'
        displayName: 'NPM Build'
